version: '0.1'

services:
  frontend:
    build: ./frontend
    ports:
      - 1002:1002
    networks:
      - diploma-network

  backend:
    build: ./backend
    command: ./back
    restart: always
    ports:
      - 9090:9090
    depends_on:
      - database
    networks:
      - diploma-network

  database:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=nymph
      - POSTGRES_PASSWORD=nymph_pwd
      - POSTGRES_DB=nymph_db
    networks:
      - diploma-network

networks:
  diploma-network:
    driver: bridge